name: "MLSpec Sample Action - Package"
description: "Sample Action Example: Package"
author: "aronchick"
inputs:
  METASTORE_CREDENTIALS:
    description: "Some text"
    required: true
branding:
  icon: "chevron-up"
  color: "blue"
runs:
  using: "docker"
  image: "Dockerfile"
